name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 14.2
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Run tests
        run: make test
